"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect } from "react";
import { supabase } from "@/lib/supabase";
import { QUERY_KEYS } from "@/lib/realtimeInvalidator";

async function fetchReportDetail(reportId) {
  // Core report — only columns that exist in the schema
  const { data: reportData, error: reportError } = await supabase
    .from("sanitation_reports")
    .select(
      `id, reference_id, issue_type, severity, health_risk, description,
       reporter_phone, status, created_at, updated_at,
       location_id, reported_by, affected_people_count, community_id,
       is_anonymous, assigned_to,
       location:locations(id, name, area_name, landmark, latitude, longitude, type, climate_risk),
       community:communities(name, district, region),
       reported_by_profile:profiles!reported_by(full_name, phone, role),
       worker:profiles!sanitation_reports_assigned_to_fkey(id, full_name, role, phone)`
    )
    .eq("id", reportId)
    .single();

  if (reportError) throw reportError;

  // Location images
  let locationImages = [];
  if (reportData?.location_id) {
    const { data: imagesData } = await supabase
      .from("location_images")
      .select("id, image_url, image_type, caption")
      .eq("location_id", reportData.location_id)
      .order("created_at", { ascending: true });
    locationImages = imagesData || [];
  }

  // Status history
  const { data: historyData } = await supabase
    .from("report_status_history")
    .select(
      `id, old_status, new_status, changed_at, notes,
       changed_by_profile:profiles!changed_by(full_name, role)`
    )
    .eq("report_id", reportId)
    .order("changed_at", { ascending: false });

  // Risk assessment (auto-generated by DB trigger on insert)
  const { data: riskData, error: riskError } = await supabase
    .from("risk_assessments")
    .select(
      `id, risk_score, priority_level, near_school, near_water_source,
       flood_zone, drought_zone, repeated_incident, affected_children_count,
       escalation_required, calculated_at`
    )
    .eq("report_id", reportId)
    .order("calculated_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  console.log("[RiskAssessment] reportId:", reportId);
  console.log("[RiskAssessment] data:", riskData);
  console.log("[RiskAssessment] error:", riskError);

  return {
    report:          reportData,
    statusHistory:   historyData || [],
    locationImages,
    riskAssessment:  riskData ?? null,
    // Keep assignments as empty array for backward compat with WorkflowRoadmap
    assignments: [],
  };
}

export function useReportDetail(reportId) {
  const qc = useQueryClient();
  const queryKey = QUERY_KEYS.reportDetail(reportId);

  const { data, isLoading: loading } = useQuery({
    queryKey,
    queryFn: () => fetchReportDetail(reportId),
    enabled: !!reportId,
  });

  // Real-time: watch this specific report for status changes
  useEffect(() => {
    if (!reportId) return;

    const channel = supabase
      .channel(`report_detail_${reportId}`)
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "sanitation_reports", filter: `id=eq.${reportId}` },
        (payload) => {
          // Patch status immediately
          qc.setQueryData(queryKey, (old) => {
            if (!old) return old;
            return {
              ...old,
              report: {
                ...old.report,
                status:     payload.new.status,
                assigned_to: payload.new.assigned_to,
                updated_at: payload.new.updated_at,
              },
            };
          });
          qc.invalidateQueries({ queryKey });
        }
      )
      .subscribe();

    return () => supabase.removeChannel(channel);
  }, [reportId, qc, queryKey]);

  return {
    report:          data?.report          ?? null,
    assignments:     data?.assignments     ?? [],
    statusHistory:   data?.statusHistory   ?? [],
    locationImages:  data?.locationImages  ?? [],
    riskAssessment:  data?.riskAssessment  ?? null,
    loading,
    refetch: () => qc.invalidateQueries({ queryKey }),
  };
}
